name: Generate AST Types Documentation

on:
  push:
    branches:
      - main

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.12.2"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Generate documentation
        run: npm run docs
